RestaurantMVCAssign/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RestaurantMVCAssign.Models
{
    public enum CusineType
    {
        None,
        Italian,
        French,
        Indian
    }

    public class Restaurant
    {
        public int RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public CusineType Cusine { get; set; }
    }
}

RestaurantMVCAssign/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantMVCAssign.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RestaurantMVCAssign/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RestaurantMVCAssign.Models;

namespace RestaurantMVCAssign.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index()
        {
            List<Restaurant>restaurants=new List<Restaurant>
            {
                new Restaurant(){RestaurantId=101, RestaurantName="Catch 35",Cusine=CusineType.French},
                new Restaurant(){RestaurantId=102, RestaurantName="Swagath",Cusine=CusineType.Indian},
                new Restaurant(){RestaurantId=103, RestaurantName="Blue Plate",Cusine=CusineType.Italian},
                new Restaurant(){RestaurantId=104, RestaurantName="Paradise",Cusine=CusineType.None},

            };
            return View(restaurants);
        }
        public ActionResult Image()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var restaurant = new List<Restaurant>
            {
                new Restaurant(){RestaurantId=101, RestaurantName="Catch 35",Cusine=CusineType.French},
                new Restaurant(){RestaurantId=102, RestaurantName="Swagath",Cusine=CusineType.Indian},
                new Restaurant(){RestaurantId=103, RestaurantName="Blue Plate",Cusine=CusineType.Italian},
                new Restaurant(){RestaurantId=104, RestaurantName="Paradise",Cusine=CusineType.None},
            };

            Restaurant reqRest = null;
            foreach (var item in restaurant)
            {
                if (item.RestaurantId == id)
                {
                    reqRest = item;

                }

            }

            return View(reqRest);
        }
    }
}

RestaurantMVCAssign/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RestaurantMVCAssign/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RestaurantMVCAssign/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

RestaurantMVCAssign/Views/Restaurant/Details.cshtml
@model RestaurantMVCAssign.Models.Restaurant
@{
    ViewBag.Title = "Details";
}

<h2>Restaurant Details</h2>

<div class="container">
    <div>
        <h3>Restaurant Id: @Model.RestaurantId</h3>
    </div>
    <div>
        <h3>Restaurant Name: @Model.RestaurantName</h3>
    </div>
    <div>
        <h3>Cusine: @Model.Cusine</h3>
    </div>

    <div>
        <a class="btn btn-default" href="/restaurant/index">Back</a>
    </div>
</div>

RestaurantMVCAssign/Views/Restaurant/Image.cshtml
@{
    ViewBag.Title = "Image";
}

<h2>Image</h2>
<img src="~/fonts/RestImg.jpg" width="1000" height="600"/>

RestaurantMVCAssign/Views/Restaurant/Index.cshtml
@model IEnumerable<RestaurantMVCAssign.Models.Restaurant>
@{
    ViewBag.Title = "Index";
}

<h2>Restaurant Names</h2>

@foreach(var rname in Model)
{
<ul>
    <li><a href="/Restaurant/details/@rname.RestaurantId"> @rname.RestaurantName</a></li>
</ul>
}

RestaurantMVCAssign/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @Html.Partial("_NavBar")
    <div class="row">

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>
    </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

RestaurantMVCAssign/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("MultiCusineRestaurants", "Image", "Restaurant")</li>
                <li>@Html.ActionLink("Restaurants", "Index", "Restaurant")</li>
                @*<li>@Html.ActionLink("Restaurant Details", "Details", "Restaurant")</li>*@

            </ul>
        </div>
    </div>
</div>